### ISSUE TITLE
Building the app

### ISSUE THREAD

**Issue by Araamarmorth** [spooky/unitdb#35]
Hi,

I'm trying to add new features and it's quite hard without building the app, so I'm trying to build it.
My best guest right now was to get node and grunt, to try to install the dependencies (which is awful to do by hand, I guess there is a nicer way), to run 'bower install'  and to run 'grunt build'.

I currently have several issues:
 - it seems from Gruntfile.js l:25 that there is supposed to be a 'local.conf.json' file in the repo root with the path where to put the minimized version, as it not currently on the repo I just hardcoded 'dist'
 - the sprites:* tasks emit "Warning: Sorry, the spritesmith engine 'phantomjs' could not be loaded. Please be sure you have installed it properly on your machine." As far as I can tell it is properly installed and working, did you use any particular set up or way to install it ? More generally do you have any idea on how to set up the dependancies ?
 -  autoprefixer:dist task says: "Warning: Cannot read property 'length' of undefined" (might be linked with the missing sprites)
 - I might do a quick documentation on how to install this properly -if I find how to do it that is-, would you be interested to put it into the repo ?

**Comment by Araamarmorth** [comment]
Grunt very optimistically states that : 

"Assuming that the Grunt CLI has been installed and that the project has already been configured with a package.json and a Gruntfile, it's very easy to start working with Grunt:

Change to the project's root directory.
Install project dependencies with npm install.
Run Grunt with grunt."
cf  http://gruntjs.com/getting-started#working-with-an-existing-grunt-project

I don't know how hard it would be to modify said package.json and Gruntfile so that it would be the case ?

**Comment by Araamarmorth** [comment]
I did a fresh install of node, npm, grunt and bower, updated those to the latest version, installed the dependencies and even the optional dependencies of the listed dependencies (btw the dependency angular-underscore is not in the npm repo so I took it from the github page of the project) but I still have the same loading phantomjs problem.
Trying to tweak the different versions of phantomjs and grunt-spritesmith didn't worked out either (for different reasons), so I can build and serve with --force but I won't get the sprites.

**Comment by spooky** [comment]
To answer your questions:
* requirements - npm install should install all the required things, so running 

        npm install
        grunt

  should get you up to speed requirements wise - if it's not the case - please report (note that the phantomjs problem is not a requirements problem, for a fix about this, see the answer below)
* angular-underscore - that doesn't need to be available in npm, it needs to be available for bower, and that is the case. Note that npm, bower and grunt are separate projects that 'just happen' to work well together.
* local.conf.json - as you can see, the 'dist' value is a fallback in case the file is not found. As the name suggests, it's a local configuration file and should **not** be committed to the repo. It's there in case you want to publish the app to a different location than the default 'dist' and don't want to type it in as a param each time you build.
* phantomjs - you need to have phantomjs in your path so that the grunt tasks are able to access it. When you npm install phantomjs, the location of the binary is not added to the path. There is a way to fix this issue (I know I've seen it work properly in other grunt templates, just haven't had time to work it out as this has low priority) - to get this up running quickly, just add phantomjs dir to your path or run a command from cmd or powershell to add it temporary (which is what I do)
* autoprefixer - this is (I assume) due to the failed previous task (phantomjs related)

**Comment by Araamarmorth** [comment]
*  `npm install & grunt` wasn't quite enough, but with enough hacking thrown at phantomjs I finally managed to make it work ! I don't know exactly what minimal sequence of actions ended up working so I'll have to sort this out sometime and write it down.

* the problem with the missing local.conf.json is that it creates an error while loading the tasks so no task any task such as test, build or default will instantly fail with *Task "X" not found*, #39 is a possible fix.

* autoprefixer was indeed failing because of previous fails.
