### ISSUE TITLE
improve filter by fixing irregularities in unit abilities

### ISSUE THREAD

**Issue by badbwoi** [spooky/unitdb#68]
Hey, first of all thanks for the great unitdb and implementing the view by class.

I frequently use the filter to search for a specific unit ability e.g. assist (Mantis, Harbinger), reclaim (Harbinger), hover and so on. But irregularities in the given units abilities makes it hard to compare stuff very easy - would be nice to change that.

At first glance "jamming", "capture" "stealth" and "shield" (Note: UEF Stealth field due to name included) are working fine. But others don't, due to missing abilities:

T1-T3 Engineers and S/ACUs - All missing "Reclaims" and "Repairs", except all Sera engineers, first Hive and UEF Sparky
Mantis - "Repairs" is displayed. I expected something like "Assists". But even engineers don't have "Assists", so  I believe "Repairs" covers that?! If I actually filter for "assist", it currently displays only the 3 hives and the T1 UEF engineering drone.
I could help with adding some abilities to the blueprints.
![repairs-assits](https://user-images.githubusercontent.com/28671151/33485331-51e69ca6-d6a6-11e7-8a66-adc2154ff94f.png)

In addition to that, it would be nice to have something like a drop-down-menu (displaying all unit abilities) for easy filtering. Maybe that way "Repairs" could count to "Assists" if selected, without implementing a new ability class.

**Comment by spooky** [comment]
The unit db is based solely on the .bp files from faf, so any inconsistencies that are here, come from the source. If you want to help with fixing these, then the righ repo to create a PR is the faf repo. Note that faf has changed quite a lot, so there are acually things that are not used by the game any more, but still displayed by the unit db.

As for the repairs - that indeed seems to be present on the mantis and harb only, but 'repair' is available on the engies... This is actually due to the fact that 'repairs' is in mantis abilities, but 'repair' is in the categories.
